Add github action CI to run tests
google/vroom pull request #122
Opened 2022-09-25 18:53 UTC by ezzieyguywuf

2022-09-29 04:43 UTC, dbarnett requested changes
Did you want to try to simplify to use `xvfb-run script` instead of all the redirection like we'd chatted about?

2022-09-29 10:49 UTC, ezzieyguywuf commented
Yes! I'll work on that later today, thanks for the reminder

El jue, 29 de sept de 2022, 12:43 a. m., David Barnett <
***@***.***> escribió:

> ***@***.**** requested changes on this pull request.
>
> Did you want to try to simplify to use xvfb-run script instead of all the
> redirection like we'd chatted about?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/google/vroom/pull/122#pullrequestreview-1124618540>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEMB5CGQVUVT3U4FTQ5VZTWAUM6HANCNFSM6AAAAAAQVGMYYQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-08-27 23:28 UTC, dbarnett commented
@ezzieyguywuf oh, we still haven't converted this repo to GitHub Actions... any interest in finishing up this PR?

2026-04-07 18:03 UTC, closed without merging

2026-04-07 18:04 UTC, ezzieyguywuf commented
closing, I have not made time to finish this in the past few  years and don't imagine I will do so in the near future.